# Generated by Django 4.2.8 on 2023-12-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_video_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='blade_type',
            field=models.CharField(choices=[('Wharncliffe', 'Wharncliffe'), ('DropPoint', 'DropPoint'), ('Tanto', 'Tanto')], default='type_klin', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('Neobrabotan', 'Без обработки'), ('Blue', 'Синий'), ('Yellow', 'Желтый'), ('Marine', 'Бирюзовый'), ('Pink', 'Розовый')], default='color', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.EmailField(default='your_default_email', max_length=254),
        ),
        migrations.AddField(
            model_name='task',
            name='first_name',
            field=models.CharField(default='first_name', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='last_name',
            field=models.CharField(default='surname', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.TextField(default='message'),
        ),
    ]
