# Generated by Django 4.2.8 on 2023-12-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_options_remove_task_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='blade_type',
            field=models.CharField(choices=[('Wharncliffe', 'Wharncliffe'), ('DropPoint', 'DropPoint'), ('Tanto', 'Tanto')], default='Форма клинка', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(choices=[('Neobrabotan', 'Без обработки'), ('Blue', 'Синий'), ('Yellow', 'Желтый'), ('Marine', 'Бирюзовый'), ('Pink', 'Розовый')], default='Цвет', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(default='Адрес электронной почты', max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='first_name',
            field=models.CharField(default='Имя', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.TextField(default='Дополнительное сообщение'),
        ),
    ]
