# Generated by Django 4.2.8 on 2024-01-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_task_blade_type_alter_task_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='handle_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='blade_type',
            field=models.CharField(choices=[('Wharncliffe', 'Wharncliffe'), ('DropPoint', 'DropPoint'), ('Tanto', 'Tanto')], default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AlterField(
            model_name='task',
            name='first_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.TextField(default=' '),
        ),
    ]
